version: '3.8'
services:
  app:
    image: 'fitchmultz/chat-with-gpt:latest'
    restart: always
    ports:
      - '3000:3000'  # Port mapping from host to container
    volumes: 
      - ${HOST_DATA_PATH}:/app/data
