name: Docker Build and Publish to GHCR

on:
  push:
    branches:
      - main
      - dev
      - dev2

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/chat-with-gpt:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/chat-with-gpt:cache
          cache-to: type=inline

      - name: Trigger Portainer Stack Update on main Branch
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}

      - name: Trigger Portainer Stack Update on dev Branch
        if: github.ref == 'refs/heads/dev'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_DEV }}

      - name: Trigger Portainer Stack Update on dev2 Branch
        if: github.ref == 'refs/heads/dev2'
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL_DEV2 }}
